version: 2 # Phiên bản cấu hình Dependabot

updates:
  - package-ecosystem: "npm" # Hệ sinh thái package dành cho Nuxt (npm)
    directory: "/" # Thư mục chứa tệp quản lý dependencies, thường là tại gốc dự án
    schedule:
      interval: "yearly" # Kiểm tra cập nhật mỗi năm (ít nhất có thể)
    commit-message:
      prefix: "chore" # Tiền tố cho commit được tạo bởi Dependabot
    open-pull-requests-limit: 0 # Không mở pull request tự động
    ignore:
      - dependency-name: "*" # Bỏ qua tất cả dependencies
        update-types: 
          - "version-update:semver-major"
          - "version-update:semver-minor"
          - "version-update:semver-patch"
